top_dir=..

all:
		letce2 \
			lxc \
			build \
			$(top_dir)/node.cfg.d/cband.cfg \
			$(top_dir)/node.cfg.d/highband.cfg \
			$(top_dir)/node.cfg.d/lowband.cfg \
			$(top_dir)/node.cfg.d/interue.cfg \
			experiment.cfg

clean:
		letce2 \
			lxc \
			clean